# Generated by Django 6.0 on 2025-12-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='Name of the news source (e.g., Financial Times)', max_length=200)),
                ('url', models.URLField(help_text='RSS feed URL', max_length=500, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('business', 'Business'), ('economics', 'Economics'), ('politics', 'Politics'), ('world', 'World'), ('markets', 'Markets'), ('climate', 'Climate'), ('geopolitics', 'Geopolitics'), ('technology', 'Technology'), ('other', 'Other')], default='general', help_text='Content category for this feed', max_length=50)),
                ('active', models.BooleanField(default=True, help_text='Whether to fetch articles from this feed')),
                ('description', models.TextField(blank=True, help_text='Optional description of this feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'ordering': ['source_name', 'category'],
            },
        ),
    ]
