# Generated by Django 6.0 on 2025-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SankeyDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/title for this diagram', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this diagram shows')),
                ('config_text', models.TextField(help_text='Sankey diagram configuration in SankeyMatic format')),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Diagram appearance settings (colors, sizes, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='user', help_text='Username or identifier of creator', max_length=100)),
                ('rendered_svg', models.TextField(blank=True, help_text='Cached SVG output')),
            ],
            options={
                'verbose_name': 'Sankey Diagram',
                'verbose_name_plural': 'Sankey Diagrams',
                'ordering': ['-updated_at'],
            },
        ),
    ]
