# Generated by Django 6.0 on 2025-12-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_delete_newsarticle'),
        ('sankey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sankeydiagram',
            name='is_published',
            field=models.BooleanField(default=False, help_text='When published, nodes become database entries linkable to articles'),
        ),
        migrations.AddField(
            model_name='sankeydiagram',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when diagram was published', null=True),
        ),
        migrations.CreateModel(
            name='PublishedNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Node name/label', max_length=500)),
                ('original_config_data', models.JSONField(blank=True, default=dict, help_text='Original node configuration (position, color, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sankey_diagram', models.ForeignKey(help_text='The diagram this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='published_nodes', to='sankey.sankeydiagram')),
            ],
            options={
                'verbose_name': 'Published Node',
                'verbose_name_plural': 'Published Nodes',
                'ordering': ['name'],
                'unique_together': {('sankey_diagram', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NodeArticleAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('association_type', models.CharField(choices=[('supporting', 'Supporting'), ('conflicting', 'Conflicting')], help_text='Whether this article supports or conflicts with the node', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Strength/confidence score for this association')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='user', help_text='Username of person who created this association', max_length=100)),
                ('article', models.ForeignKey(help_text='The news article', on_delete=django.db.models.deletion.CASCADE, related_name='node_associations', to='articles.preprocessingarticle')),
                ('node', models.ForeignKey(help_text='The published node', on_delete=django.db.models.deletion.CASCADE, related_name='article_associations', to='sankey.publishednode')),
            ],
            options={
                'verbose_name': 'Node-Article Association',
                'verbose_name_plural': 'Node-Article Associations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['association_type'], name='sankey_node_associa_594537_idx'), models.Index(fields=['score'], name='sankey_node_score_9fe19a_idx')],
                'unique_together': {('node', 'article')},
            },
        ),
    ]
