# Generated by Django 6.0 on 2025-12-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('link', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('category', models.TextField(blank=True, null=True)),
                ('feed_url', models.TextField(blank=True, null=True)),
                ('guid', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreprocessingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('source', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('feed_url', models.TextField(blank=True)),
                ('guid', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=500)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(default='SYSTEM', max_length=100)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('outcome', models.CharField(choices=[('NEW', 'New'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='NEW', max_length=20)),
                ('storygroup', models.CharField(blank=True, max_length=200)),
                ('source_article_id', models.IntegerField(blank=True, help_text='ID from news.db', null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_added'],
                'indexes': [models.Index(fields=['outcome'], name='articles_pr_outcome_401296_idx'), models.Index(fields=['source'], name='articles_pr_source_ccc387_idx'), models.Index(fields=['storygroup'], name='articles_pr_storygr_19c7d0_idx'), models.Index(fields=['time_added'], name='articles_pr_time_ad_64599a_idx')],
                'unique_together': {('title', 'source', 'published')},
            },
        ),
    ]
